Repository Team-Umbba/Umbba-iOS, pull requests merged in 2023-08, with the labels that each got.

#172 [Fix] #171 - NetworkConstant 오류 수정
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS.xcodeproj/xcshareddata/xcschemes/Umbba-iOS.xcscheme
  Umbba-iOS/Umbba-iOS/Global/Resources/Lottie/ViewController/LottieViewController.swift
  Umbba-iOS/Umbba-iOS/Network/Base/NetworkConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Services/ArchivingListService.swift
  Umbba-iOS/Umbba-iOS/Network/Services/AuthService.swift
  Umbba-iOS/Umbba-iOS/Network/Services/HomeService.swift
  Umbba-iOS/Umbba-iOS/Network/Services/OnBoardingService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/InviteViewController/InviteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/View/MainView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/ViewController/CompleteViewController.swift
Labels: ⚒️Fix, 🐥영린

#177 [Feat] #176 - QA 및 피드백 반영
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Item/ArchivingQuestionItem.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/View/ArchivingCollectionView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라

#180 [Feat] #179 - 엔딩뷰 UI 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_ending_img.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_ending_img.imageset/Group 14089.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_ending_img.imageset/Group 14089@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_ending_img.imageset/Group 14089@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ending_img.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ending_img.imageset/찐최종엽서임요-01 1.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ending_img.imageset/찐최종엽서임요-01 1@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ending_img.imageset/찐최종엽서임요-01 1@3x.png
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/ViewController/ArchivingViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EndingScene/View/EndingView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EndingScene/ViewController/EndingViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBarController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🎨UI

#183 [Chore] #174 - 기획 측 QA사항 및 변경사항 반영
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Application/AppDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/View/InviteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/NoticeAlarmScene/ViewController/NoticeAlarmViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/PushAlarmScene/ViewController/PushAlarmViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/View/UserInfoView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/ViewController/UserInfoViewController.swift
Labels: 🪄Chore, 🐥영린

#184 [Feat] #178 - 로딩뷰UI 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Presentation/Common/Loading/View/LoadingView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Loading/splash_clear_iOS.json
Labels: 🦖유진, 👩🏻‍💻Feat

#182 [Feat] #181 - 엔딩뷰 로직 구현
  Umbba-iOS/Umbba-iOS/Application/Manager/User/UserManager.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ending_img.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ending_img.imageset/ending.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ending_img.imageset/ending@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ending_img.imageset/ending@3x.png
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EndingScene/View/EndingView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EndingScene/ViewController/EndingViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/View/MainView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라

#188 [Fix] #186 - 수정 사항 반영
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/kakaoLogo.imageset/ri_kakao-talk-fill.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/kakaoLogo.imageset/ri_kakao-talk-fill@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/kakaoLogo.imageset/ri_kakao-talk-fill@3x.png
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/ViewController/ArchivingViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EndingScene/View/EndingView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EndingScene/ViewController/EndingViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/View/LoginView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/AccountViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawalViewController.swift
Labels: 🐰아라, ⚒️Fix

#189 [Chore] #185 - 초대코드 공유 메세지 변경, 푸시알림 클릭시 특정 뷰 이동 및 오류 수정
  Umbba-iOS/Umbba-iOS/Application/AppDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBarController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/View/AnswerWriteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/View/QuestView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/ViewController/QuestViewController.swift
Labels: 🪄Chore, 🐥영린

#193 [Fix] #192 - 엔딩뷰 로직 수정
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBarController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
Labels: 🐰아라, ⚒️Fix

#191 [Chore] #190 - 온보딩 이미지 변경 및 로딩뷰 추가
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/Loading.dataset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/Loading.dataset/Loading.gif
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive_SE_img.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive_SE_img.imageset/iPhone SE - 4@1x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive_SE_img.imageset/iPhone SE - 4@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive_SE_img.imageset/iPhone SE - 4@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive_img.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive_img.imageset/도착 이미지@1x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive_img.imageset/도착 이미지@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive_img.imageset/도착 이미지@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/departure_SE_img.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/departure_SE_img.imageset/iPhone SE - 6@1x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/departure_SE_img.imageset/iPhone SE - 6@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/departure_SE_img.imageset/iPhone SE - 6@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/departure_img.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/departure_img.imageset/도착 이미지2@1x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/departure_img.imageset/도착 이미지2@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/departure_img.imageset/도착 이미지2@3x.png
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/View/InviteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Loading/View/LoadingView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBarController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/View/AnswerDetailView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
Labels: 🪄Chore, 🦖유진, 🐥영린
