Repository Team-Umbba/Umbba-iOS, pull requests merged in 2023-09, with the labels that each got.

#195 [Chore] #194 - 이미지 오류 수정 및 테플 업데이트
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Application/AppDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive_img.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive_img.imageset/arrive_img@1x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive_img.imageset/arrive_img@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive_img.imageset/arrive_img@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/departure_img.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/departure_img.imageset/depart_img@1x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/departure_img.imageset/depart_img@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/departure_img.imageset/depart_img@3x.png
  Umbba-iOS/Umbba-iOS/Info.plist
  Umbba-iOS/Umbba-iOS/Presentation/Auth/AssignScene/ViewController/AssignViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Loading/View/LoadingView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBarController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/View/AnswerDetailView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/View/QuestView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/View/UserInfoView.swift
Labels: 🪄Chore, 🐥영린

#197 [Chore] #196 - 기획 측 변경사항 반영
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/AccountViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawalViewController.swift
Labels: 🪄Chore, 🐥영린

#199 [Fix] #198 - 아카이빙뷰 레이아웃 수정
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Cell/ArchivingQuestionTableHeaderView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Cell/ArchivingQuestionTableViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/View/ArchivingCollectionView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/View/ArchivingSectionCollectionView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/View/ArchivingTableView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/ViewController/ArchivingViewController.swift
Labels: 🐰아라, ⚒️Fix, 🎨UI

#202 [Chore] #200 - 동적 링크 클릭 시 이동뷰 분기처리
  Umbba-iOS/Umbba-iOS/Application/SceneDelegate.swift
  Umbba-iOS/Umbba-iOS/Umbba-iOS.entitlements
Labels: 🪄Chore, 🐥영린

#204 [Feat] #201 - 뒤로가기 스와이프 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Resources/Lottie/ViewController/LottieViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/InviteViewController/InviteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/Main.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/ViewController/AnswerWriteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/ViewController/CompleteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/FamilyInfoScene/ViewController/FamilyInfoViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/NoticeAlarmScene/ViewController/NoticeAlarmViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/PushAlarmScene/ViewController/PushAlarmViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/ViewController/QuestViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/ViewController/UserInfoViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/AccountViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라
