Repository Team-Umbba/Umbba-iOS, pull requests merged in 2023-10, with the labels that each got.

#205 [Setting] #203 - Crashlytics 세팅
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
Labels: 🐥영린, ⚙️Setting

#207 [Feat] #206 - 업데이트 팝업 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Utils/AppStoreCheck.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/InviteAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/UpdateAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/ViewController/AlertVIewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBarController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린

#213 [Feat] #208 - 교신화면 고도화 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Extension/UIImage+.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Animation/AnimationGif.gif
  Umbba-iOS/Umbba-iOS/Global/Resources/Animation/AnimationMp4.mp4
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/WriteSaveAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/AnimationScene/View/AnimationView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/AnimationScene/ViewController/AnimationViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라

#212 [Feat] #209 - 동적링크 클릭시 초대코드 자동 입력 및 답변화면 줄 수 제한 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Application/SceneDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UITextVeiw+.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/InviteViewController/InviteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/View/InviteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBarController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/View/AnswerWriteView.swift
Labels: 👩🏻‍💻Feat, 🐥영린

#211 [Feat] #210 - 특수문자 블러처리
  Umbba-iOS/Umbba-iOS/Global/Utils/BlurredLabel.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/View/AnswerDetailView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat
