Repository Team-Umbba/Umbba-iOS, pull requests merged in 2023-07, with the labels that each got.

#2 [Setting] #1 - 프로젝트 초기 세팅
  Umbba-iOS/Umbba-iOS/.swiftlint.yml
  Umbba-iOS/Umbba-iOS/Application/AppDelegate.swift
  Umbba-iOS/Umbba-iOS/Application/Manager/User/UserManager.swift
  Umbba-iOS/Umbba-iOS/Application/SceneDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/NSObject+.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UIButton+.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UIImage+.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UILabel+.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UIStackView+.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UITableView+.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UITextField+.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UIVIew+.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UIViewController+.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/ColorLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/FontLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/SizeLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Protocols/UICollectionViewRegisterable.swift
  Umbba-iOS/Umbba-iOS/Global/Protocols/UITableViewRegiseterable.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Font/Font.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Lottie/Lottie.swift
  Umbba-iOS/Umbba-iOS/Global/Supporting Files/Base.lproj/LaunchScreen.storyboard
  Umbba-iOS/Umbba-iOS/Global/Utils/ButtonPress.swift
  Umbba-iOS/Umbba-iOS/Global/Utils/MakeVibrate.swift
  Umbba-iOS/Umbba-iOS/Info.plist
  Umbba-iOS/Umbba-iOS/Network/Base/NetworkResult.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/User.swift
  Umbba-iOS/Umbba-iOS/Network/Enviornment/Config.swift
  Umbba-iOS/Umbba-iOS/Network/Services/AuthService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Archiving.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/Entry.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/invite.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/Login.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBar.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/UIComponents/UIComponents.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/Detail.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/Main.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/Write.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/AnimationScene/Animation.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/Complete.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/FamilyInfoScene/FamilyInfo.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/NoticeAlarmScene/NoticeAlarm.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/PushAlarmScene/PushAlarm.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/Quest.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/UserInfo.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/Setting.swift
  Umbba-iOS/Umbba-iOS/Presentation/Splash/SplashScene/Splash.swift
  Umbba-iOS/Umbba-iOS/ViewController.swift
Labels: 🐥영린, ⚙️Setting

#4 [Setting] #3 - 폰트, 컬러 디자인시스템 추가
  .gitignore
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Extension/UIColor+.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/ColorLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/FontLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Font/Cafe24Classictype-v1.1.otf
  Umbba-iOS/Umbba-iOS/Global/Resources/Font/Font.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Font/Pretendard-Bold.otf
  Umbba-iOS/Umbba-iOS/Global/Resources/Font/Pretendard-Regular.otf
  Umbba-iOS/Umbba-iOS/Global/Resources/Font/Pretendard-SemiBold.otf
  Umbba-iOS/Umbba-iOS/Info.plist
Labels: 🐥영린, ⚙️Setting

#7 [Feat] #5 - UIComponent - CustomButton, CustomTextField 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Presentation/Common/UIComponents/CustomButton.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/UIComponents/CustomTextField.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/UIComponents/UIComponents.swift
Labels: 👩🏻‍💻Feat, 🐥영린

#9 [Feat] #8 - 초대코드입력 뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Extension/String+.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UILabel+.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/View/InviteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/ViewController/InviteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/invite.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🎨UI

#13 [Feat] #6 - 타임머신 공지 뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/NoticeAlarmScene/NoticeAlarm.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/NoticeAlarmScene/View/NoticeAlarmView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/NoticeAlarmScene/ViewController/NoticeAlarmViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat, 🎨UI

#11 [Feat] #10 - 로그인 뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Application/SceneDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/Entry.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/View/EntryView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/ViewController/EntryViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/Login.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/View/LoginView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🎨UI

#15 [Feat] #12 - 유저 정보 입력 뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Extension/UIVIew+.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/View/UserInfoView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/ViewController/UserInfoViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🎨UI

#18 [Feat] #14 - 설정 뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Application/SceneDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/Setting.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingSectionHeaderView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingTableViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat, 🎨UI

#19 [Feat] #17 - 가족 정보 입력 뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/FamilyInfoScene/View/FamilyInfoView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/FamilyInfoScene/ViewController/FamilyInfoViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🎨UI

#22 [Feat]#21 - 온보딩 완료 뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/ColorLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/UIComponents/CustomTextField.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/View/CompleteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/ViewController/CompleteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/FamilyInfoScene/View/FamilyInfoView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/View/UserInfoView.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🎨UI

#26 [Feat] #20 - TabBarController 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/ColorLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home_active.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home_active.imageset/home_active.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home_active.imageset/home_active@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home_active.imageset/home_active@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home_default.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home_default.imageset/home_defalt.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home_default.imageset/home_defalt@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home_default.imageset/home_defalt@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/list_active.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/list_active.imageset/list_active.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/list_active.imageset/list_active@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/list_active.imageset/list_active@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/list_default.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/list_default.imageset/list_defalt.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/list_default.imageset/list_defalt@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/list_default.imageset/list_defalt@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/setting_active.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/setting_active.imageset/setting_active.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/setting_active.imageset/setting_active@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/setting_active.imageset/setting_active@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/setting_default.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/setting_default.imageset/setting_defalt.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/setting_default.imageset/setting_defalt@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/setting_default.imageset/setting_defalt@3x.png
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBarController.swift
Labels: 🦖유진, 👩🏻‍💻Feat, 🎨UI

#28 [Fix] #27 - 빌드 오류 수정
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/InviteViewController/InviteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/LoginView/LoginView.swift
Labels: ⚒️Fix, 🐥영린

#30 [Feat] #25 - 답변 작성 뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/View/AnswerWriteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/ViewController/AnswerWriteViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🎨UI

#32 [Feat] #31 - UIComponent - CustomNavigationBar 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Application/SceneDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/back.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/back.imageset/back@1x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/back.imageset/back@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/back.imageset/back@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/check.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/check.imageset/check@1x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/check.imageset/check@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/check.imageset/check@3x.png
  Umbba-iOS/Umbba-iOS/Presentation/Common/UIComponents/CustomNavigationBar.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/View/AnswerWriteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/ViewController/AnswerWriteViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🎨UI

#34 [Feat] #33 - 팝업뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Extension/UIViewController+.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/WithdrawalAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/WriteCancelAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/WriteSaveAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/ViewController/AlertVIewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/View/AnswerWriteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/ViewController/AnswerWriteViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🎨UI

#37 [Feat] #29 - 설정 테이블뷰 섹션 추가
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Extension/UIVIew+.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/Setting.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/AccountTableView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingSectionHeaderView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingTableView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingTableViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/AccountViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat, 🎨UI

#36 [Feat] #35 - 초대하기 팝업 뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/exit.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/exit.imageset/exit@1x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/exit.imageset/exit@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/exit.imageset/exit@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/umbbaLogo.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/umbbaLogo.imageset/umbbaLogo@1x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/umbbaLogo.imageset/umbbaLogo@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/umbbaLogo.imageset/umbbaLogo@3x.png
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/InviteAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/ViewController/AlertVIewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🎨UI

#38 [Feat] #16 아카이빙 뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Cell/ArchivingQuestionCollectionViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Cell/ArchivingQuestionHeaderView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Cell/ArchivingSectionCollectionViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Item/ArchivingQuestionItem.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/View/ArchivingCollectionView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/View/ArchivingImageView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/ViewController/ArchivingViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🎨UI

#42 [Chore] #41 - 푸시 알림 공지뷰 변경된 디자인 반영
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Protocols/NaviagionBarProtocol.swift
  Umbba-iOS/Umbba-iOS/Global/Protocols/NextButtonProtocol.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/View/AnswerWriteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/ViewController/AnswerWriteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/NoticeAlarmScene/View/NoticeAlarmView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/NoticeAlarmScene/ViewController/NoticeAlarmViewController.swift
Labels: 🪄Chore, 🐥영린, 🎨UI

#44 [Feat] #39 계정 관리 뷰 구현
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/AccountTableView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingSectionHeaderView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingTableView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingTableViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/AccountViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat, 🎨UI

#46 [Feat] #40 사용자 동의 화면 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/circle_check.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/circle_check.imageset/circle_check.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/circle_check.imageset/circle_check@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/circle_check.imageset/circle_check@3x.png
  Umbba-iOS/Umbba-iOS/Presentation/Auth/AssignScene/View/AssignView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/AssignScene/ViewController/AssignViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🎨UI

#48 [Chore] #43 - 온보딩 파트 화면 전환 구현
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/InviteViewController/InviteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/View/InviteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/View/CompleteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/ViewController/CompleteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/FamilyInfoScene/View/FamilyInfoView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/FamilyInfoScene/ViewController/FamilyInfoViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/PushAlarmScene/View/PushAlarmView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/PushAlarmScene/ViewController/PushAlarmViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/View/UserInfoView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/ViewController/UserInfoViewController.swift
Labels: 🪄Chore, 🐥영린

#50 [Feat] #45 - 설정 테이블뷰셀 웹뷰 연결
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/AccountTableView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingSectionHeaderView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingTableView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingTableViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/AccountViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat

#51 [Chore] #47 시작 화면 디자인 반영 및 화면 전환 구현
  Umbba-iOS/Umbba-iOS/Global/Literals/ColorLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/appleLogo.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/appleLogo.imageset/ic_baseline-apple.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/appleLogo.imageset/ic_baseline-apple@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/appleLogo.imageset/ic_baseline-apple@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/kakaoLogo.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/kakaoLogo.imageset/ri_kakao-talk-fill.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/kakaoLogo.imageset/ri_kakao-talk-fill@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/kakaoLogo.imageset/ri_kakao-talk-fill@3x.png
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/View/EntryView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/ViewController/EntryViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/LoginView/LoginView.swift
Labels: 🪄Chore, 🐰아라, 🎨UI

#54 [Chore] #49 - 온보딩 뷰 디자인, UX 변경사항 반영 및 버튼 Gradient 추가
  Umbba-iOS/Umbba-iOS/Global/Literals/ColorLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/View/InviteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/UIComponents/CustomButton.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/UIComponents/CustomTextField.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/View/CompleteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/FamilyInfoScene/View/FamilyInfoView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/PushAlarmScene/View/PushAlarmView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/View/UserInfoView.swift
Labels: 🪄Chore, 🐥영린, 🎨UI

#57 [Feat] #52 - AnswerDetail 문답화면 구현하기
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/View/AnswerDetailView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/ViewController/AnswerWriteViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat, 🎨UI

#55 [Feat] #53 - 스플래쉬 화면 로티 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Application/SceneDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Lottie/View/LottieView.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Lottie/ViewController/LottieViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🎨UI

#64 [Fix] #63 - splash.json 파일 추가 및 빌드오류 해결
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Resources/Lottie/View/LottieView.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Lottie/splash_iOS.json
Labels: 🦖유진, ⚒️Fix

#60 [Feat] #56 - 초대하기 뷰 연결 및 플로우 구현
  Umbba-iOS/Umbba-iOS/Global/Extension/String+.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/View/EntryView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/ViewController/EntryViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/InviteViewController/InviteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/View/InviteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBarController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/UIComponents/CustomButton.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/ViewController/CompleteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/FamilyInfoScene/View/FamilyInfoView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/View/UserInfoView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/ViewController/UserInfoViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린

#65 [Feat] #59 - 회원 탈퇴 뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Lottie/ViewController/LottieViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/WithdrawalView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/AccountViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawalViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat, 🎨UI

#71 [Setting] #69 - 소셜로그인 및 FCM 세팅
  .gitignore
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Application/AppDelegate.swift
  Umbba-iOS/Umbba-iOS/Application/SceneDelegate.swift
  Umbba-iOS/Umbba-iOS/Info.plist
  Umbba-iOS/Umbba-iOS/Umbba-iOS.entitlements
Labels: 🐥영린, ⚙️Setting

#74 [Add] #73 - GoogleService 파일 재추가
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
Labels: ⚒️Fix, 🐥영린

#68 [Feat] #66 - 답변 작성 내용 팝업뷰 연결
  Umbba-iOS/Umbba-iOS/Global/Extension/UIViewController+.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/WriteSaveAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/ViewController/AlertVIewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/View/AnswerWriteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/ViewController/AnswerWriteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/Write.swift
Labels: 👩🏻‍💻Feat, 🐥영린

#76 [Feat] #72 - 사용자 동의 화면 웹뷰 연결 및 UI 수정
  Umbba-iOS/Umbba-iOS/Application/SceneDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UILabel+.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/AssignScene/View/AssignView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/AssignScene/ViewController/AssignViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🎨UI

#80 [Chore] #78 - 푸시알림 기본 시간 설정 및 Formatted Time 형식 변경
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/PushAlarmScene/ViewController/PushAlarmViewController.swift
Labels: 🪄Chore, 🐥영린, 🎨UI

#81 [Feat] #67 - 문답화면 분기처리
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Utils/BlurredLabel.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/View/AnswerDetailView.swift
Labels: 🦖유진, 👩🏻‍💻Feat

#85 [Feat] #83 - 소셜 로그인 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/View/LoginView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🌐Network

#87 [Feat] #82 - 팝업 뷰 추가 구현 및 메인화면 질문하기 버튼 분기처리
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/icn_disconnect.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/icn_disconnect.imageset/icn_disconnect@1x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/icn_disconnect.imageset/icn_disconnect@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/icn_disconnect.imageset/icn_disconnect@3x.png
  Umbba-iOS/Umbba-iOS/Global/Utils/ShowToast.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/DisconnectAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/InviteAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/WriteCancelAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/ViewController/AlertVIewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/View/MainView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/View/AnswerWriteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/ViewController/AnswerWriteViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🎨UI

#88 [Fix] #84 - 탭바 컨트롤러 오류 해결
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBarController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/View/AnswerDetailView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
Labels: 🦖유진, ⚒️Fix

#89 [Feat] #75 - 단답질문 UI 구현 및 초대 받는 측 화면 전환 분기처리
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/FamilyInfoScene/ViewController/FamilyInfoViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/Cell/QuestCollectionCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/View/QuestView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/ViewController/QuestViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/ViewController/UserInfoViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🎨UI

#92 [Feat] #90 - 질문 확인하기 버튼 시 화면 전환 처리
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/WriteCancelAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat

#94 [Setting] #91 - 네트워크 초기 세팅
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Info.plist
  Umbba-iOS/Umbba-iOS/Network/Base/BaseService.swift
  Umbba-iOS/Umbba-iOS/Network/Base/GenericResponse.swift
  Umbba-iOS/Umbba-iOS/Network/Base/NetworkConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Base/URLConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/ArchivingList/Detail/DetailEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/ArchivingList/List/ListEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Auth/Login/LoginEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Auth/Logout/LogoutEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Auth/PushAlarm/PushAlarmEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Auth/ReIssue/ReIssueEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Answer/AnswerEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Main/MainEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Response/ResponseEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Today/TodayEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/OnBoarding/Invite/InviteEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/OnBoarding/Match/MatchEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/OnBoarding/Receive/ReceiveEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Enviornment/Config.swift
  Umbba-iOS/Umbba-iOS/Network/Services/ArchivingListService.swift
  Umbba-iOS/Umbba-iOS/Network/Services/AuthService.swift
  Umbba-iOS/Umbba-iOS/Network/Services/HomeService.swift
  Umbba-iOS/Umbba-iOS/Network/Services/OnBoardingService.swift
Labels: 🐥영린, ⚙️Setting

#95 [Feat] #93 - 교신 뷰 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive.imageset/arrive.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive.imageset/arrive@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/arrive.imageset/arrive@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/depart.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/depart.imageset/depart.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/depart.imageset/depart@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/depart.imageset/depart@3x.png
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/WriteSaveAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/AnimationScene/View/AnimationView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/AnimationScene/ViewController/AnimationViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat, 🎨UI

#98 [Feat] #96 - 메인 화면 API 구현
  Umbba-iOS/Umbba-iOS/Global/Literals/SizeLiterals.swift
  Umbba-iOS/Umbba-iOS/Network/Base/NetworkConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Base/URLConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Main/MainEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Services/HomeService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/View/MainView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🌐Network

#101 [Feat] #97 - 온보딩 완료 화면 애니메이션 구현 및 화면 전환 분기 처리 추가
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/back.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/ViewController/EntryViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/InviteViewController/InviteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/AnimationScene/ViewController/AnimationViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/View/CompleteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/ViewController/CompleteViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🎨UI

#103 [Feat] 메인 화면 및 리스트 화면 레이아웃 수정
  Umbba-iOS/Umbba-iOS/Global/Resources/Lottie/ViewController/LottieViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Cell/ArchivingQuestionCollectionViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Cell/ArchivingSectionCollectionViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/View/ArchivingImageView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/ViewController/ArchivingViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🎨UI

#104 [Feat] #99 - 최근 질문과 답변 조회 API 연결
  Umbba-iOS/Umbba-iOS/Network/Base/URLConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Answer/AnswerEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Services/HomeService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/View/AnswerDetailView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat, 🌐Network

#106 [Feat] #102 - 초대코드입력 API 연결
  Umbba-iOS/Umbba-iOS/Network/Entity/OnBoarding/Match/MatchEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Services/OnBoardingService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/InviteViewController/InviteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/View/InviteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🌐Network

#109 [Feat] #105 - 초대코드 반환 API 연결
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Extension/UIViewController+.swift
  Umbba-iOS/Umbba-iOS/Network/Base/URLConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Answer/AnswerEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Main/CaseEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Today/TodayEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Services/HomeService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/View/InviteAlertView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/ViewController/AlertVIewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/View/AnswerDetailView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat, 🌐Network

#111 [Feat] #107 - 답변 작성 API 연결 및 문답 화면 API 수정
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Network/Base/URLConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Answer/AnswerEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Answer/AnswerEntity2.swift
  Umbba-iOS/Umbba-iOS/Network/Services/HomeService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/View/AnswerDetailView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/ViewController/AnswerWriteViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🌐Network

#108 [Feat] #100 - 아카이빙 화면 API 연결
  Umbba-iOS/Umbba-iOS/Network/Base/NetworkConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Base/URLConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/ArchivingList/List/ListEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Services/ArchivingListService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Cell/ArchivingQuestionCollectionViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Cell/ArchivingQuestionHeaderView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Cell/ArchivingSectionCollectionViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/View/ArchivingImageView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/ViewController/ArchivingViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🌐Network

#115 [Feat] #112 - 단답 질문 로직 구현 및 데이터 처리
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Utils/BlurredLabel.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/PushAlarmScene/ViewController/PushAlarmViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/Cell/QuestCollectionCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/ViewController/QuestViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린

#121 [Feat] #119 - 로그인뷰 배경 이미지 추가
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_login.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_login.imageset/SE_login.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_login.imageset/SE_login@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_login.imageset/SE_login@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_start.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_start.imageset/SE _start.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_start.imageset/SE _start@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_start.imageset/SE _start@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/login_img.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/login_img.imageset/login_img.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/login_img.imageset/login_img@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/login_img.imageset/login_img@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/start_img.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/start_img.imageset/start_img.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/start_img.imageset/start_img@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/start_img.imageset/start_img@3x.png
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/View/EntryView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/View/LoginView.swift
Labels: 🦖유진, 👩🏻‍💻Feat, 🎨UI

#122 [Feat] #117 - 문답 개별 조회 API 연결
  Umbba-iOS/Umbba-iOS/Network/Base/URLConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/ArchivingList/Detail/DetailEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Services/ArchivingListService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/View/ArchivingCollectionView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/ViewController/ArchivingViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/View/AnswerDetailView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🌐Network

#125 [Feat] #116 - 카카오톡 메세지 구현
  Umbba-iOS/Umbba-iOS/Info.plist
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린

#126 [Feat] #120 - 온보딩 API 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Network/Base/URLConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Auth/WithDrawal/WithDrawalEntity/WithDrawalEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Answer/AnswerEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Answer/AnswerEntity2.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/OnBoarding/Invite/InviteEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/OnBoarding/Match/MatchEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/OnBoarding/Receive/ReceiveEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Services/HomeService.swift
  Umbba-iOS/Umbba-iOS/Network/Services/OnBoardingService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/ViewController/EntryViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/InviteViewController/InviteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/AnimationScene/ViewController/AnimationViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/ViewController/CompleteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/FamilyInfoScene/View/FamilyInfoView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/PushAlarmScene/ViewController/PushAlarmViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/ViewController/QuestViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserData.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/View/UserInfoView.swift
Labels: 👩🏻‍💻Feat, 🐥영린

#128 [Feat] #124 - 로그인 및 회원가입 API 연결
  Umbba-iOS/Umbba-iOS/Application/AppDelegate.swift
  Umbba-iOS/Umbba-iOS/Application/Manager/User/UserManager.swift
  Umbba-iOS/Umbba-iOS/Global/Utils/makeAlert.swift
  Umbba-iOS/Umbba-iOS/Network/Base/URLConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Auth/Login/LoginEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Services/AuthService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🌐Network

#133 [Fix] #132 - 파일 오류 수정
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Utils/MakeAlert.swift
Labels: 🐰아라, ⚒️Fix

#131 [Feat] #123 - 문답화면/질문답변화면 데이터전달
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBarController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/TodayData.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/View/AnswerWriteView.swift
Labels: 🦖유진, 👩🏻‍💻Feat

#129 [Chore] #127 - 초대하기 측, 초대 받는 측 API 통신 측 분기처리
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/InviteViewController/InviteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/ViewController/CompleteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/NoticeAlarmScene/ViewController/NoticeAlarmViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/PushAlarmScene/ViewController/PushAlarmViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/ViewController/QuestViewController.swift
Labels: 🪄Chore, 🐥영린, 🌐Network

#136 [Chore] 유저 정보 화면 키보드 처리 및 ToolBar 추가
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Application/AppDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UIResponder+.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/UIViewController+.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Utils/AddToolBar.swift
  Umbba-iOS/Umbba-iOS/Info.plist
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/View/EntryView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/View/InviteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/View/CompleteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/ViewController/CompleteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/Cell/QuestCollectionCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/View/UserInfoView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/ViewController/UserInfoViewController.swift
Labels: 🪄Chore, 🐥영린

#138 [Feat] #134 - 자동 로그인 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Application/AppDelegate.swift
  Umbba-iOS/Umbba-iOS/Application/Manager/User/UserDefaultWrapper.swift
  Umbba-iOS/Umbba-iOS/Application/Manager/User/UserManager.swift
  Umbba-iOS/Umbba-iOS/Application/SceneDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Lottie/ViewController/LottieViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/AssignScene/View/AssignView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/View/LoginView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🌐Network

#140 [Feat] #137 - 푸시 알림 팝업화면 특정 화면에서 뜨게 하기
  Umbba-iOS/Umbba-iOS/Application/AppDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Extension/String+.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/NoticeAlarmScene/ViewController/NoticeAlarmViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/PushAlarmScene/ViewController/PushAlarmViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린

#142 [Feat] #135 - NoticeAlarmView 시간 단위 분기처리
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/NoticeAlarmScene/View/NoticeAlarmView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingSectionHeaderView.swift
Labels: 🦖유진, ⚒️Fix

#143 [Fix] #139 - 메인 화면 오류 해결
  Umbba-iOS/Umbba-iOS/Network/Base/NetworkConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Auth/Login/LoginEntity.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/View/AnswerDetailView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
Labels: 🐰아라, ⚒️Fix

#145 [Chore] #144 - 이미지 에셋 추가
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/I.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/I.imageset/home2.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/I.imageset/home2@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/I.imageset/home2@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_arrive.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_arrive.imageset/iPhone SE - 4.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_arrive.imageset/iPhone SE - 4@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_arrive.imageset/iPhone SE - 4@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_depart.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_depart.imageset/iPhone SE - 6.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_depart.imageset/iPhone SE - 6@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_depart.imageset/iPhone SE - 6@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home1.imageset/SE_home1.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home1.imageset/SE_home1@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home1.imageset/SE_home1@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home2.imageset/SE_home2.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home2.imageset/SE_home2@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home2.imageset/SE_home2@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home3.imageset/SE_home3.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home3.imageset/SE_home3@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home3.imageset/SE_home3@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home4.imageset/SE_home4.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home4.imageset/SE_home4@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home4.imageset/SE_home4@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home5.imageset/SE_home5.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home5.imageset/SE_home5@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home5.imageset/SE_home5@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home1.imageset/home1.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home1.imageset/home1@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home1.imageset/home1@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home2.imageset/home2.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home2.imageset/home2@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home2.imageset/home2@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home3.imageset/home3.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home3.imageset/home3@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home3.imageset/home3@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home4.imageset/home4.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home4.imageset/home4@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home4.imageset/home4@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home5.imageset/home5.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home5.imageset/home5@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home5.imageset/home5@3x.png
Labels: 🪄Chore, 🐰아라

#149 [Feat] #147 - 데이터 전달 오류 수정
  Umbba-iOS/Umbba-iOS/Application/Manager/User/UserManager.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home2.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home2.imageset/home2.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home2.imageset/home2@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/home2.imageset/home2@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Lottie/ViewController/LottieViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/Cell/ArchivingSectionCollectionViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/ViewController/ArchivingViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/ViewController/EntryViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/AccountViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawalViewController.swift
Labels: 🐰아라, ⚒️Fix

#148 [Feat] #146 - 알람 설정 on/off 권한설정
  Umbba-iOS/Umbba-iOS/Application/Manager/User/UserManager.swift
  Umbba-iOS/Umbba-iOS/Application/SceneDelegate.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/PushAlarmScene/ViewController/PushAlarmViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/View/SettingSectionHeaderView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
Labels: 🦖유진, 👩🏻‍💻Feat

#154 [Fix] #151 - 초대코드 분기처리 수정
  Umbba-iOS/Umbba-iOS/Application/Manager/User/UserManager.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/OnBoarding/Match/MatchEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Services/OnBoardingService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/ViewController/EntryViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/InviteScene/InviteViewController/InviteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/ViewController/CompleteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/QuestScene/ViewController/QuestViewController.swift
Labels: 🐰아라, ⚒️Fix

#158 [Feat] #156 - QA 반영
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/View/AnswerDetailView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/NoticeAlarmScene/ViewController/NoticeAlarmViewController.swift
Labels: 🪄Chore, 🦖유진

#159 [Feat] #155 - QA 반영
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home1.imageset/SE_home1.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home1.imageset/SE_home1@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home1.imageset/SE_home1@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home2.imageset/SE_home2.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home2.imageset/SE_home2@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home2.imageset/SE_home2@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home3.imageset/SE_home3.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home3.imageset/SE_home3@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home3.imageset/SE_home3@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home4.imageset/SE_home4.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home4.imageset/SE_home4@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home4.imageset/SE_home4@3x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home5.imageset/SE_home5.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home5.imageset/SE_home5@2x.png
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/SE_home5.imageset/SE_home5@3x.png
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/ViewController/ArchivingViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/AssignScene/View/AssignView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/View/EntryView.swift
Labels: 🪄Chore, 🐰아라

#160 [Chore] #157 - QA 반영
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Archiving/ArchivingScene/ViewController/ArchivingViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/Alert/ViewController/AlertVIewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/View/AnswerWriteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/WriteScene/Write.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/View/UserInfoView.swift
Labels: 🪄Chore, 🐥영린

#162 [Chore] #161 - 레이아웃 수정 및 버튼 타이틀 변경
  Umbba-iOS/Umbba-iOS/Presentation/Auth/AssignScene/View/AssignView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EntryScene/View/EntryView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/LoginScene/View/LoginView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/AnimationScene/View/AnimationView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/View/CompleteView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/CompleteScene/ViewController/CompleteViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Onboarding/UserInfoScene/View/UserInfoView.swift
Labels: 🪄Chore, 🐰아라
