Repository Team-Umbba/Umbba-iOS, pull requests merged in 2024-02, with the labels that each got.

#224 [Fix] #223 - 업데이트 확인 로직 Lottie로 변경
  Umbba-iOS/Umbba-iOS/Application/AppDelegate.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Lottie/ViewController/LottieViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/TabBar/TabBarController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
Labels: ⚒️Fix, 🐥영린

#227 [Chore] #226 - 기존 ImageLiterals 방식으로 통일
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Common/UIComponents/CustomNavigationBar.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/MyPageScene/View/MyPageView.swift
Labels: 🪄Chore, 🐥영린

#228 [Feat] #218 - 기록하기뷰 UI 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_camera.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_camera.imageset/ic_camera 1.svg
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_camera.imageset/ic_camera 2.svg
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_camera.imageset/ic_camera.svg
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_closeQuote.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_closeQuote.imageset/ic_closeQuote 1.svg
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_closeQuote.imageset/ic_closeQuote 2.svg
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_closeQuote.imageset/ic_closeQuote.svg
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_exit.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_exit.imageset/ic_exit 1.svg
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_exit.imageset/ic_exit 2.svg
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_exit.imageset/ic_exit.svg
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_openQuote.imageset/Contents.json
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_openQuote.imageset/ic_openQuote 1.svg
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_openQuote.imageset/ic_openQuote 2.svg
  Umbba-iOS/Umbba-iOS/Global/Resources/Assets.xcassets/ic_openQuote.imageset/ic_openQuote.svg
  Umbba-iOS/Umbba-iOS/Presentation/Common/UIComponents/CustomNavigationBar.swift
  Umbba-iOS/Umbba-iOS/Presentation/Record/RecordScene/Cell/RecordCollectionViewCell.swift
  Umbba-iOS/Umbba-iOS/Presentation/Record/RecordScene/View/RecordView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Record/RecordScene/ViewController/RecordViewController.swift
Labels: 👩🏻‍💻Feat, 🐰아라, 🎨UI

#230 [Chore] #229 - 마이페이지 UI 변경사항 반영
  Umbba-iOS/Umbba-iOS/Global/Literals/ImageLiterals.swift
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/Presentation/Record/RecordScene/View/RecordView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Record/RecordScene/ViewController/RecordViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/MyPageScene/View/MyPageView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/MyPageScene/ViewController/MyPageViewController.swift
Labels: 🪄Chore, 🐥영린, 🎨UI

#232 [Fix] #231 - 회원탈퇴 뷰에서 BackButton 안되는 이슈 해결
  Umbba-iOS/Umbba-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawalViewController.swift
Labels: ⚒️Fix, 🐥영린

#235 [Setting] #234 - 개발서버, 운영서버 분리로 인한 BaseURL 세팅 변경
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
Labels: 🐥영린, ⚙️Setting

#237 [Feat] #236 - 마이페이지 API 연결 및 초대코드 팝업 구현
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS/MyPageEntity.swift
  Umbba-iOS/Umbba-iOS/MyPageService.swift
  Umbba-iOS/Umbba-iOS/Network/Base/URLConstant.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/MyPageScene/View/MyPageView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Setting/MyPageScene/ViewController/MyPageViewController.swift
Labels: 👩🏻‍💻Feat, 🐥영린, 🌐Network, 🎨UI

#239 [Feat] #233 - 엔딩페이지 ui 및 서버 수정사항 반영
  Umbba-iOS/Umbba-iOS.xcodeproj/project.pbxproj
  Umbba-iOS/Umbba-iOS.xcodeproj/xcshareddata/xcschemes/Umbba-iOS.xcscheme
  Umbba-iOS/Umbba-iOS/Global/Literals/StringLiterals.swift
  Umbba-iOS/Umbba-iOS/MyPageEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Base/URLConstant.swift
  Umbba-iOS/Umbba-iOS/Network/Entity/Home/Restart/RestartEntity.swift
  Umbba-iOS/Umbba-iOS/Network/Services/HomeService.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EndingScene/View/EndingView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Auth/EndingScene/ViewController/EndingViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/DetailScene/ViewController/AnswerDetailViewController.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/View/MainView.swift
  Umbba-iOS/Umbba-iOS/Presentation/Home/MainScene/ViewController/MainViewController.swift
Labels: 🐰아라, ⚒️Fix, 🌐Network, 🎨UI
